spring:
  application.name: billing-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/billing-service?currentSchema=account
    username: postgres
    password: password
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.yml
    default-schema: account
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ru-oleynik-otus-billing-service
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "ru.oleynik.otus.common.kafka.*"
    listener:
      ack-mode: record

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

application:
  kafka:
    enabled: true
    back-off:
      interval: 100
      max-attempts: 5
